### ISSUE TITLE
Consider shortening test output

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust-test-runner#7]
While working with the Rust test runner, I found that test failure messages are quite verbose:

```
thread 'test_01' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `327`', tests/rust_1_a.rs:17:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at /rustc/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/libstd/io/mod.rs:1426
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:212
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:463
  12: rust_begin_unwind
             at src/libstd/panicking.rs:371
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:325
  14: rust_1_a::test_01
             at tests/rust_1_a.rs:11
  15: rust_1_a::test_01::{{closure}}
             at tests/rust_1_a.rs:10
  16: core::ops::function::FnOnce::call_once
             at /rustc/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/libcore/ops/function.rs:232
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/liballoc/boxed.rs:1015
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  19: std::panicking::try
             at /rustc/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/libstd/panicking.rs:272
  20: std::panic::catch_unwind
             at /rustc/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/libstd/panic.rs:394
  21: test::run_test_in_process
             at src/libtest/lib.rs:540
  22: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm wondering if including the stack trace actually helps the student here. If not, it might be useful to remove the stack trace from the output, which would also help not expose some of our externals.

**Comment by coriolinus** [comment]
Yeah, it's unfortunate that you don't see your code in the stack trace until level 14. 

I'm of mixed minds about this. On the one hand, stack traces can be really useful whenever there's an actual panic. On the other hand, 99% of the time, a stack trace in a test suite failure will be caused by an assertion failure within the test. 

It's not hard to disable this; we just need to remove the line setting an environment variable in `run.sh`. 

On the balance, I think this is a good idea.
